/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721UriStorageSol from "./ERC721URIStorage.sol";
export type { erc721UriStorageSol };
export type { PermissionStorage } from "./PermissionStorage";
export type { SampleERC20 } from "./SampleERC20";
