/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721UriStorageSol from "./ERC721URIStorage.sol";
export { PermissionStorage__factory } from "./PermissionStorage__factory";
export { SampleERC20__factory } from "./SampleERC20__factory";
